### ISSUE TITLE
KeyError: 'songs'

### ISSUE THREAD

**Issue by yoiyami96** [maxesisn/nonebot_plugin_songpicker2#2]
File "src/plugins\nonebot_plugin_songpicker2\data_source.py", line 105, in songInfo
    songInfo["songName"] = r["songs"][0]["name"]
KeyError: 'songs'

**Comment by xuxiaolong-hascats** [comment]
File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_songpicker2/data_source.py", line 105, in songInfo
    songInfo["songName"] = r["songs"][0]["name"]
KeyError: 'songs

**Comment by sfvsfv** [comment]
> File "src/plugins\nonebot_plugin_songpicker2\data_source.py", line 105, in songInfo
> songInfo["songName"] = r["songs"][0]["name"]
> KeyError: 'songs'

+1

**Comment by maxesisn** [comment]
master分支已提交更改以显示更详细的接口返回数据，请在更新后查看网易云接口具体返回的数据以便于debug。
（我刚刚试了一下发现很容易触发网易的网络错误信息，可能报错是由此原因造成的，改天我再从[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)项目里抄点更稳定的东西过来

**Comment by sfvsfv** [comment]
已读，不在。
