### ISSUE TITLE
这个是什么问题啊

### ISSUE THREAD

**Issue by yhzcake** [maxesisn/nonebot_plugin_songpicker2#7]
![image](https://user-images.githubusercontent.com/80627671/187067890-4772e86c-7d77-4bc5-b52a-1dc99d4c4b02.png)

**Comment by maxesisn** [comment]
1. 这个是好老的写法了，现在已经不用这个方法了；
2. 请尝试[py38](https://github.com/maxesisn/nonebot_plugin_songpicker2/tree/py38)分支。
